import { UserRole } from "../types";

export type FieldType = "text" | "number" | "date" | "datetime" | "boolean" | "select" | "textarea" | "json" | "url";

export interface CollectionFieldSchema {
  key: string;
  label: string;
  type: FieldType;
  required?: boolean;
  readonly?: boolean;
  options?: string[];
  placeholder?: string;
  help?: string;
}

export interface CollectionSchema {
  collection: string;
  title: string;
  description: string;
  primaryKey: string;
  orderBy?: string;
  fields: CollectionFieldSchema[];
}

const statusOptions = ["SUBMITTED", "APPROVED", "WAITING_TRANSFER", "TRANSFERRED", "WAITING_CLEARANCE", "PARTIALLY_CLEARED", "ACCOUNTING_REVIEW", "CLOSED", "REJECTED", "RETURNED", "DRAFT", "PENDING_APPROVAL", "PENDING_AUDIT", "WAITING_ORIGINAL_DOC"];
const clearingStatusOptions = ["DRAFT", "PENDING", "APPROVED", "RETURNED", "PARTIAL"];
const activeStatusOptions = ["Active", "ACTIVE", "Completed", "COMPLETED", "Suspended", "SUSPENDED", "Disabled"];
const completenessOptions = ["COMPLETE", "PARTIAL", "MISSING", "NOT_REQUIRED"];
const ocrStatusOptions = ["PENDING", "PROCESSING", "SUCCESS", "FAILED", "SKIPPED"];

export const COLLECTION_SCHEMAS: CollectionSchema[] = [
  {
    collection: "employees",
    title: "Employees / ข้อมูลพนักงาน",
    description: "ข้อมูลคนในระบบทั้งหมด ใช้กับสิทธิ์อนุมัติ Dashboard และ Google Sheets",
    primaryKey: "employeeId",
    orderBy: "employeeCode",
    fields: [
      { key: "employeeId", label: "Employee ID", type: "text", required: true },
      { key: "employeeCode", label: "รหัสพนักงาน", type: "text", required: true },
      { key: "name", label: "ชื่อ-นามสกุล", type: "text", required: true },
      { key: "nickname", label: "ชื่อเล่น", type: "text" },
      { key: "username", label: "Username", type: "text", required: true },
      { key: "role", label: "บทบาท", type: "select", required: true, options: Object.values(UserRole) },
      { key: "status", label: "สถานะ", type: "select", options: ["Active", "Disabled", "Suspended"] },
      { key: "lineUserId", label: "LINE User ID", type: "text" },
      { key: "bankName", label: "ธนาคาร", type: "text" },
      { key: "bankNo", label: "เลขบัญชี", type: "text" },
      { key: "bankAccountName", label: "ชื่อบัญชี", type: "text" },
      { key: "profileImage", label: "รูปโปรไฟล์", type: "url" },
      { key: "signatureUrl", label: "ลายเซ็น", type: "url" },
    ],
  },
  {
    collection: "projects",
    title: "Projects / ทะเบียนโครงการ",
    description: "ข้อมูลโครงการหลัก ควรใช้ projectId เป็นตัวเชื่อมหลักแทนชื่อโครงการ",
    primaryKey: "projectId",
    orderBy: "projectCode",
    fields: [
      { key: "projectId", label: "Project ID", type: "text", required: true },
      { key: "projectCode", label: "รหัสโครงการ", type: "text", required: true },
      { key: "projectName", label: "ชื่อโครงการ", type: "text", required: true },
      { key: "companyName", label: "บริษัท", type: "text" },
      { key: "clientName", label: "ลูกค้า", type: "text" },
      { key: "pmId", label: "PM ID", type: "text" },
      { key: "pmName", label: "PM Name", type: "text" },
      { key: "contractAmount", label: "มูลค่าสัญญา", type: "number" },
      { key: "budget", label: "งบประมาณ", type: "number" },
      { key: "pettyCashBudget", label: "งบเงินทดรอง", type: "number" },
      { key: "startDate", label: "วันที่เริ่ม", type: "date" },
      { key: "endDate", label: "วันที่สิ้นสุด", type: "date" },
      { key: "status", label: "สถานะ", type: "select", options: activeStatusOptions },
      { key: "location", label: "สถานที่", type: "text" },
    ],
  },
  {
    collection: "project_costs",
    title: "Project Costs / สรุปต้นทุนโครงการ",
    description: "ตัวเลขการเงินของโครงการ ใช้โหลด Dashboard และรายงานโดยไม่ต้อง sum ทุกครั้ง",
    primaryKey: "projectId",
    orderBy: "projectName",
    fields: [
      { key: "projectId", label: "Project ID", type: "text", required: true },
      { key: "projectName", label: "ชื่อโครงการ", type: "text", required: true },
      { key: "contractBudget", label: "งบสัญญา", type: "number" },
      { key: "pettyCashBudget", label: "งบเงินทดรอง", type: "number" },
      { key: "totalAdvanceRequested", label: "ยอดขอเบิกสะสม", type: "number" },
      { key: "totalAdvanceApproved", label: "ยอดอนุมัติสะสม", type: "number" },
      { key: "totalClearingSubmitted", label: "ยอดส่งเคลียร์สะสม", type: "number" },
      { key: "totalClearingApproved", label: "ยอดเคลียร์อนุมัติ", type: "number" },
      { key: "outstandingAmount", label: "ยอดค้างเคลียร์", type: "number" },
      { key: "remainingPettyCashBudget", label: "งบคงเหลือ", type: "number" },
      { key: "variance", label: "Variance", type: "number" },
      { key: "riskScore", label: "Risk Score", type: "number" },
      { key: "waitingApprovalAmount", label: "รออนุมัติ", type: "number" },
      { key: "waitingTransferAmount", label: "รอโอน", type: "number" },
      { key: "waitingClearanceAmount", label: "รอเคลียร์", type: "number" },
      { key: "overdueAmount", label: "ยอดเกินกำหนด", type: "number" },
      { key: "overdueCount", label: "จำนวนเกินกำหนด", type: "number" },
      { key: "clearanceRate", label: "Clearance Rate", type: "number" },
      { key: "advanceExposure", label: "Advance Exposure", type: "number" },
      { key: "lastUpdatedAt", label: "อัปเดตล่าสุด", type: "datetime" },
    ],
  },
  {
    collection: "advances",
    title: "Advances / ใบขอเบิกเงิน",
    description: "ใบเบิกเงินทดรองหลัก ใช้กับ workflow, dashboard และ cash locked",
    primaryKey: "advId",
    orderBy: "createdAt",
    fields: [
      { key: "advId", label: "เลข ADV", type: "text", required: true },
      { key: "employeeId", label: "Employee ID", type: "text", required: true },
      { key: "employeeName", label: "ผู้ขอเบิก", type: "text", required: true },
      { key: "projectId", label: "Project ID", type: "text", required: true },
      { key: "projectName", label: "ชื่อโครงการ", type: "text" },
      { key: "category", label: "หมวดหมู่", type: "text" },
      { key: "requestAmount", label: "ยอดขอเบิก", type: "number" },
      { key: "approvedAmount", label: "ยอดอนุมัติ", type: "number" },
      { key: "approvedBy", label: "อนุมัติโดย", type: "text" },
      { key: "approvedAt", label: "อนุมัติเมื่อ", type: "datetime" },
      { key: "transferredAt", label: "โอนเมื่อ", type: "datetime" },
      { key: "outstandingAmount", label: "ยอดค้างเคลียร์", type: "number" },
      { key: "approvedClearingAmountTotal", label: "ยอดเคลียร์อนุมัติรวม", type: "number" },
      { key: "status", label: "สถานะ", type: "select", options: statusOptions },
      { key: "transferSlipUrl", label: "สลิปโอน", type: "url" },
      { key: "details", label: "รายละเอียด", type: "textarea" },
      { key: "neededDate", label: "วันที่ต้องใช้เงิน", type: "date" },
      { key: "createdAt", label: "สร้างเมื่อ", type: "datetime" },
    ],
  },
  {
    collection: "clearingLogs",
    title: "Clearing Logs / หัวใบเคลียร์",
    description: "รอบการเคลียร์ของแต่ละ ADV หนึ่ง ADV อาจมีหลายรอบ",
    primaryKey: "clearingLogId",
    orderBy: "submittedAt",
    fields: [
      { key: "clearingLogId", label: "Clearing Log ID", type: "text", required: true },
      { key: "advId", label: "เลข ADV", type: "text", required: true },
      { key: "roundNo", label: "รอบที่", type: "number" },
      { key: "submittedAt", label: "ส่งเมื่อ", type: "datetime" },
      { key: "submittedBy", label: "ส่งโดย", type: "text" },
      { key: "totalSubmittedAmount", label: "ยอดส่งเคลียร์", type: "number" },
      { key: "totalApprovedAmount", label: "ยอดอนุมัติ", type: "number" },
      { key: "status", label: "สถานะ", type: "select", options: clearingStatusOptions },
      { key: "accountantNote", label: "หมายเหตุบัญชี", type: "textarea" },
      { key: "returnedReason", label: "เหตุผลตีกลับ", type: "textarea" },
    ],
  },
  {
    collection: "clearingItems",
    title: "Clearing Items / รายการค่าใช้จ่าย",
    description: "รายละเอียดใบเสร็จ/ใบกำกับภาษี ใช้บัญชี VAT/WHT/OCR และรายงาน supplier",
    primaryKey: "itemId",
    orderBy: "createdAt",
    fields: [
      { key: "itemId", label: "Item ID", type: "text", required: true },
      { key: "advId", label: "เลข ADV", type: "text", required: true },
      { key: "clearingLogId", label: "Clearing Log ID", type: "text" },
      { key: "documentType", label: "ประเภทเอกสาร", type: "select", options: ["Receipt", "Tax Invoice", "Invoice", "Other"] },
      { key: "documentDate", label: "วันที่เอกสาร", type: "date" },
      { key: "vendorName", label: "Vendor", type: "text" },
      { key: "vendorTaxId", label: "เลขผู้เสียภาษี Vendor", type: "text" },
      { key: "invoiceNo", label: "เลขใบกำกับ/ใบเสร็จ", type: "text" },
      { key: "itemName", label: "รายการ", type: "text" },
      { key: "qty", label: "จำนวน", type: "number" },
      { key: "unitPrice", label: "ราคาต่อหน่วย", type: "number" },
      { key: "amount", label: "ยอดก่อนปรับ", type: "number" },
      { key: "discount", label: "ส่วนลด", type: "number" },
      { key: "vatType", label: "VAT Type", type: "select", options: ["INCLUDED", "EXCLUDED", "NONE"] },
      { key: "vatAmount", label: "VAT", type: "number" },
      { key: "whtRate", label: "WHT Rate", type: "select", options: ["NONE", "1%", "3%", "5%"] },
      { key: "whtAmount", label: "WHT", type: "number" },
      { key: "netAmount", label: "Net Amount", type: "number" },
      { key: "ocrConfidence", label: "OCR Confidence", type: "number" },
      { key: "isDuplicate", label: "เอกสารซ้ำ", type: "boolean" },
      { key: "imageUrl", label: "รูปเอกสาร", type: "url" },
      { key: "lineItems", label: "Line Items JSON", type: "json", help: "ใช้ array สำหรับแตกเป็น ClearingItemLines ใน Google Sheets" },
      { key: "projectSplits", label: "Project Splits JSON", type: "json", help: "ใช้ array สำหรับแตกเป็น ProjectSplits ใน Google Sheets" },
    ],
  },
  {
    collection: "clearingItemLines",
    title: "Clearing Item Lines / รายการย่อย",
    description: "รายการย่อยสินค้า/บริการจาก clearingItems.lineItems สำหรับ pivot/report",
    primaryKey: "lineId",
    fields: [
      { key: "lineId", label: "Line ID", type: "text", required: true },
      { key: "itemId", label: "Item ID", type: "text", required: true },
      { key: "advId", label: "เลข ADV", type: "text" },
      { key: "clearingLogId", label: "Clearing Log ID", type: "text" },
      { key: "itemName", label: "รายการ", type: "text" },
      { key: "qty", label: "จำนวน", type: "number" },
      { key: "unitPrice", label: "ราคาต่อหน่วย", type: "number" },
      { key: "amount", label: "ยอดรวม", type: "number" },
    ],
  },
  {
    collection: "projectSplits",
    title: "Project Splits / แบ่งต้นทุนหลายโครงการ",
    description: "แบ่งค่าใช้จ่ายใบเดียวไปหลาย project เพื่อคำนวณต้นทุนโครงการจริง",
    primaryKey: "splitId",
    fields: [
      { key: "splitId", label: "Split ID", type: "text", required: true },
      { key: "itemId", label: "Item ID", type: "text", required: true },
      { key: "advId", label: "เลข ADV", type: "text" },
      { key: "projectId", label: "Project ID", type: "text" },
      { key: "projectName", label: "ชื่อโครงการ", type: "text" },
      { key: "amount", label: "ยอดเงิน", type: "number" },
      { key: "percent", label: "เปอร์เซ็นต์", type: "number" },
    ],
  },
  {
    collection: "vaultFiles",
    title: "Vault Files / ไฟล์เอกสารแนบ",
    description: "เอกสารแนบและ Google Drive metadata สำหรับ Document Vault/OCR",
    primaryKey: "fileId",
    orderBy: "uploadedAt",
    fields: [
      { key: "fileId", label: "File ID", type: "text", required: true },
      { key: "advId", label: "เลข ADV", type: "text" },
      { key: "fileName", label: "ชื่อไฟล์", type: "text" },
      { key: "fileType", label: "ประเภทไฟล์", type: "select", options: ["REQUEST", "SLIP", "RECEIPT", "SETTLEMENT", "LOG", "OTHER"] },
      { key: "fileUrl", label: "File URL", type: "url" },
      { key: "uploadedBy", label: "อัปโหลดโดย", type: "text" },
      { key: "uploadedAt", label: "อัปโหลดเมื่อ", type: "datetime" },
      { key: "driveFolderId", label: "Drive Folder ID", type: "text" },
      { key: "driveFolderUrl", label: "Drive Folder URL", type: "url" },
      { key: "driveFileId", label: "Drive File ID", type: "text" },
      { key: "driveFileUrl", label: "Drive File URL", type: "url" },
      { key: "mimeType", label: "MIME Type", type: "text" },
      { key: "fileSize", label: "File Size", type: "number" },
      { key: "fileHash", label: "File Hash", type: "text" },
      { key: "ocrStatus", label: "OCR Status", type: "select", options: ocrStatusOptions },
    ],
  },
  {
    collection: "document_tracking",
    title: "Document Tracking / ติดตามเอกสารต้นฉบับ",
    description: "ติดตามเอกสารจริง ใบกำกับภาษี ใบเสร็จ และความครบถ้วนเอกสาร",
    primaryKey: "trackingId",
    orderBy: "updatedAt",
    fields: [
      { key: "trackingId", label: "Tracking ID", type: "text", required: true },
      { key: "documentNo", label: "เลขเอกสาร", type: "text", required: true },
      { key: "documentType", label: "ประเภทเอกสาร", type: "select", options: ["ADVANCE_REQUEST", "CLEARING", "RECEIPT", "TAX_INVOICE", "OTHER"] },
      { key: "employeeName", label: "พนักงาน", type: "text" },
      { key: "projectName", label: "โครงการ", type: "text" },
      { key: "amount", label: "ยอดเงิน", type: "number" },
      { key: "status", label: "สถานะ", type: "select", options: statusOptions },
      { key: "createdAt", label: "สร้างเมื่อ", type: "date" },
      { key: "updatedAt", label: "อัปเดตเมื่อ", type: "date" },
      { key: "originalRequired", label: "ต้องใช้ตัวจริง", type: "boolean" },
      { key: "originalReceived", label: "ได้รับตัวจริงแล้ว", type: "boolean" },
      { key: "receivedAt", label: "รับเมื่อ", type: "datetime" },
      { key: "receivedBy", label: "รับโดย", type: "text" },
      { key: "documentCompleteness", label: "ความครบถ้วน", type: "select", options: completenessOptions },
      { key: "note", label: "หมายเหตุ", type: "textarea" },
    ],
  },
  {
    collection: "GL",
    title: "GL / บัญชีแยกประเภท",
    description: "รายการเดบิต/เครดิตสำหรับรายงานบัญชีและ export ให้ฝ่ายบัญชี",
    primaryKey: "id",
    orderBy: "date",
    fields: [
      { key: "id", label: "GL ID", type: "text", required: true },
      { key: "docNo", label: "เลขเอกสาร", type: "text" },
      { key: "date", label: "วันที่", type: "date" },
      { key: "accountCode", label: "รหัสบัญชี", type: "text" },
      { key: "accountName", label: "ชื่อบัญชี", type: "text" },
      { key: "category", label: "หมวดหมู่", type: "text" },
      { key: "description", label: "คำอธิบาย", type: "textarea" },
      { key: "debit", label: "Debit", type: "number" },
      { key: "credit", label: "Credit", type: "number" },
      { key: "employeeName", label: "พนักงาน", type: "text" },
      { key: "projectId", label: "Project ID", type: "text" },
      { key: "projectName", label: "โครงการ", type: "text" },
    ],
  },
  {
    collection: "auditLogs",
    title: "Audit Logs / ประวัติการทำรายการ",
    description: "ประวัติการเปลี่ยนสถานะและการกระทำในระบบ",
    primaryKey: "auditId",
    orderBy: "timestamp",
    fields: [
      { key: "auditId", label: "Audit ID", type: "text", required: true },
      { key: "advId", label: "เลข ADV", type: "text" },
      { key: "actionType", label: "Action Type", type: "text" },
      { key: "actionBy", label: "ทำโดย", type: "text" },
      { key: "role", label: "Role", type: "select", options: Object.values(UserRole) },
      { key: "beforeStatus", label: "สถานะก่อน", type: "text" },
      { key: "afterStatus", label: "สถานะหลัง", type: "text" },
      { key: "note", label: "หมายเหตุ", type: "textarea" },
      { key: "timestamp", label: "เวลา", type: "datetime" },
    ],
  },
  {
    collection: "aiUsageLogs",
    title: "AI Usage Logs / ประวัติการใช้ AI",
    description: "ติดตามต้นทุน AI, OCR, Import และ error",
    primaryKey: "id",
    orderBy: "timestamp",
    fields: [
      { key: "id", label: "Log ID", type: "text", required: true },
      { key: "taskType", label: "Task Type", type: "select", options: ["OCR", "CHAT", "ESTIMATE", "IMPORT"] },
      { key: "model", label: "Model", type: "text" },
      { key: "promptTokens", label: "Prompt Tokens", type: "number" },
      { key: "completionTokens", label: "Completion Tokens", type: "number" },
      { key: "estimatedCostThb", label: "Cost THB", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["SUCCESS", "FAILED"] },
      { key: "userId", label: "User ID", type: "text" },
      { key: "userName", label: "User Name", type: "text" },
      { key: "timestamp", label: "เวลา", type: "datetime" },
    ],
  },
  {
    collection: "dashboard_cache",
    title: "Dashboard Cache / แคช Dashboard",
    description: "ข้อมูลสรุปเพื่อให้ Dashboard และ AI Q&A โหลดเร็ว",
    primaryKey: "cacheId",
    fields: [
      { key: "cacheId", label: "Cache ID", type: "text", required: true },
      { key: "periodType", label: "Period Type", type: "select", options: ["DAY", "WEEK", "MONTH", "QUARTER", "YEAR"] },
      { key: "dateStart", label: "วันที่เริ่ม", type: "date" },
      { key: "dateEnd", label: "วันที่สิ้นสุด", type: "date" },
      { key: "company", label: "บริษัท", type: "text" },
      { key: "outstandingAmount", label: "ยอดค้าง", type: "number" },
      { key: "waitingApprovalCount", label: "จำนวนรออนุมัติ", type: "number" },
      { key: "waitingTransferCount", label: "จำนวนรอโอน", type: "number" },
      { key: "waitingClearanceCount", label: "จำนวนรอเคลียร์", type: "number" },
      { key: "accountingReviewCount", label: "จำนวนรอบัญชี", type: "number" },
      { key: "closedCount", label: "จำนวนปิดแล้ว", type: "number" },
      { key: "clearanceRate", label: "Clearance Rate", type: "number" },
      { key: "topProjects", label: "Top Projects JSON", type: "json" },
      { key: "topEmployees", label: "Top Employees JSON", type: "json" },
      { key: "topSuppliers", label: "Top Suppliers JSON", type: "json" },
      { key: "updatedAt", label: "อัปเดตเมื่อ", type: "datetime" },
    ],
  },
  {
    collection: "executive_ai",
    title: "Executive AI / คำตอบผู้บริหาร",
    description: "เก็บคำถาม/คำตอบผู้บริหารให้ตรงกับ Dashboard และไม่ต้อง generate ใหม่ทุกครั้ง",
    primaryKey: "questionId",
    fields: [
      { key: "questionId", label: "Question ID", type: "text", required: true },
      { key: "category", label: "หมวดคำถาม", type: "text" },
      { key: "question", label: "คำถาม", type: "textarea" },
      { key: "answer", label: "คำตอบ", type: "textarea" },
      { key: "dateStart", label: "วันที่เริ่ม", type: "date" },
      { key: "dateEnd", label: "วันที่สิ้นสุด", type: "date" },
      { key: "company", label: "บริษัท", type: "text" },
      { key: "generatedAt", label: "สร้างเมื่อ", type: "datetime" },
    ],
  },
  {
    collection: "settings",
    title: "Settings / ตั้งค่าระบบ",
    description: "ตั้งค่าระบบแบบ document-based เช่น global, categories, documentTypes, runningNumbers",
    primaryKey: "id",
    fields: [
      { key: "id", label: "Document ID", type: "text", required: true, placeholder: "global" },
      { key: "projects", label: "Projects JSON", type: "json" },
      { key: "categories", label: "Categories JSON", type: "json" },
      { key: "documentTypes", label: "Document Types JSON", type: "json" },
      { key: "documentFormats", label: "Document Formats JSON", type: "json" },
      { key: "aiConfig", label: "AI Config JSON", type: "json" },
      { key: "lineConfig", label: "LINE Config JSON", type: "json" },
      { key: "googleWorkspace", label: "Google Workspace JSON", type: "json" },
      { key: "approvalWorkflow", label: "Approval Workflow JSON", type: "json" },
    ],
  },
];

export const CORE_SHEET_COLLECTIONS = [
  "employees",
  "projects",
  "project_costs",
  "advances",
  "clearingLogs",
  "clearingItems",
  "clearingItemLines",
  "projectSplits",
  "vaultFiles",
  "document_tracking",
  "GL",
  "auditLogs",
  "settings",
];

export const EXTRA_SHEET_COLLECTIONS = ["aiUsageLogs", "dashboard_cache", "executive_ai", "syncLog"];

export function getCollectionSchema(collectionName: string) {
  return COLLECTION_SCHEMAS.find((schema) => schema.collection === collectionName);
}
